In [20]:
import numpy as np  
import matplotlib.pyplot as plt
data_ori=np.loadtxt('/home/clark/Desktop/data explore/eular angle/beta_orientations.txt')

# max of the mean

In [27]:
data_mean_beta= np.loadtxt('/home/clark/Desktop/data explore/concentration 1000 orientation/beta_mean.txt')

print(np.max(data_mean_beta))

pos_beta=np.where(data_mean_beta == np.amax(data_mean_beta))
print(pos_beta)

print(data_ori[pos_beta])

1.3959737011614728
(array([141]),)
[[233.8771  71.5152 189.4676]]


In [28]:
data_mean_lam1= np.loadtxt('/home/clark/Desktop/data explore/concentration 1000 orientation/lam1_mean.txt')

print(np.max(data_mean_lam1))

pos_lam1=np.where(data_mean_lam1 == np.amax(data_mean_lam1))
print(pos_lam1)

print(data_ori[pos_lam1])

1.3913096398520255
(array([141]),)
[[233.8771  71.5152 189.4676]]


In [29]:
data_mean_lam2= np.loadtxt('/home/clark/Desktop/data explore/concentration 1000 orientation/lam2_mean.txt')

print(np.max(data_mean_lam2))

pos_lam2=np.where(data_mean_lam2 == np.amax(data_mean_lam2))
print(pos_lam2)

print(data_ori[pos_lam2])

1.3931779643672526
(array([141]),)
[[233.8771  71.5152 189.4676]]


In [31]:
data_mean_lam3= np.loadtxt('/home/clark/Desktop/data explore/concentration 1000 orientation/lam3_mean.txt')

print(np.max(data_mean_lam3))

pos_lam3=np.where(data_mean_lam3 == np.amax(data_mean_lam3))
print(pos_lam3)

print(data_ori[pos_lam3])

1.394993656145421
(array([141]),)
[[233.8771  71.5152 189.4676]]


# highest possible value (max of the max)

In [33]:
data_max_beta=np.loadtxt('/home/clark/Desktop/data explore/concentration 1000 orientation/beta_max.txt')

print(np.max(data_max_beta))

pos_max_beta=np.where(data_max_beta== np.amax(data_max_beta))
print(pos_max_beta)

print(data_ori[pos_max_beta])

2.2620151867
(array([270]),)
[[100.4058  35.8874  30.7628]]


In [35]:
data_max_lam1=np.loadtxt('/home/clark/Desktop/data explore/concentration 1000 orientation/lam1_max.txt')

print(np.max(data_max_lam1))

pos_max_lam1=np.where(data_max_lam1== np.amax(data_max_lam1))
print(pos_max_lam1)

print(data_ori[pos_max_lam1])

2.41425073
(array([317]),)
[[126.2267  74.9532 289.343 ]]


In [36]:
data_max_lam2=np.loadtxt('/home/clark/Desktop/data explore/concentration 1000 orientation/lam2_max.txt')

print(np.max(data_max_lam2))

pos_max_lam2=np.where(data_max_lam2== np.amax(data_max_lam2))
print(pos_max_lam2)

print(data_ori[pos_max_lam2])

2.3545999284
(array([317]),)
[[126.2267  74.9532 289.343 ]]


In [37]:
data_max_lam3=np.loadtxt('/home/clark/Desktop/data explore/concentration 1000 orientation/lam3_max.txt')

print(np.max(data_max_lam3))

pos_max_lam3=np.where(data_max_lam3== np.amax(data_max_lam3))
print(pos_max_lam3)

print(data_ori[pos_max_lam3])

2.3753752885
(array([270]),)
[[100.4058  35.8874  30.7628]]
